#include "PluginProcessor.h"
#include "WebViewEditor.h"

#include <cstddef>
#include <vector>

// Generated by juce_add_binary_data() in CMakeLists.txt with
// NAMESPACE {{PLUGIN_ID}}_UI. juceaide derives each symbol from the filename,
// so Source/UI/index.html becomes index_html / index_html_size.
namespace {{PLUGIN_ID}}_UI
{
    extern const char *index_html; extern const int index_html_size;
    extern const char *style_css;  extern const int style_css_size;
    extern const char *app_js;     extern const int app_js_size;
}

// Defined before use — a `static` free function declared after the constructor
// that calls it is a compile error, not a forward reference.
namespace
{
    juce::StringPairArray parseQuery (const juce::String &url)
    {
        juce::StringPairArray params;
        const auto query = url.fromFirstOccurrenceOf ("?", false, false);

        for (const auto &part : juce::StringArray::fromTokens (query, "&", ""))
        {
            const auto kv = juce::StringArray::fromTokens (part, "=", "");

            if (kv.size() == 2)
                params.set (kv[0].trim(), juce::URL::removeEscapeChars (kv[1].trim()));
        }

        return params;
    }

    // WebView2 is the backend we asked CMake for via NEEDS_WEBVIEW2 TRUE.
    // Everywhere else the platform default (WebKit / gtk-webkit2) is correct.
    juce::WebBrowserComponent::Options makeBrowserOptions (juce::WebBrowserComponent::ResourceProvider provider)
    {
        auto options = juce::WebBrowserComponent::Options{}.withResourceProvider (std::move (provider));

       #if JUCE_WINDOWS
        options = options.withBackend (juce::WebBrowserComponent::Options::Backend::webview2);
       #endif

        return options;
    }
}

WebViewEditor::WebViewEditor ({{PLUGIN_CLASS_NAME}} &p)
    : juce::AudioProcessorEditor (&p),
      m_processor (p),
      m_webView (makeBrowserOptions ([this] (const juce::String &url) { return getResource (url); }))
{
    setSize (600, 400);

    // JS -> C++: the UI navigates to apc://callback?action=...&data=... and we
    // consume it in pageAboutToLoad before any navigation happens.
    m_webView.onNavigate = [this] (const juce::String &url) { return handleJSAction (url); };

    addAndMakeVisible (m_webView);

    // Requesting the resource-provider root makes the provider receive "/", which
    // we answer with index.html.
    m_webView.goToURL (juce::WebBrowserComponent::getResourceProviderRoot());

    startTimerHz (30); // 30 fps state push
}

WebViewEditor::~WebViewEditor()
{
    stopTimer();
}

void WebViewEditor::resized()
{
    m_webView.setBounds (getLocalBounds());
}

std::optional<juce::WebBrowserComponent::Resource> WebViewEditor::getResource (const juce::String &url)
{
    // "/" is the initial document request; anything else is a sub-resource path.
    const auto wanted = url == "/" ? juce::String ("index.html")
                                   : url.fromFirstOccurrenceOf ("/", false, false);

    struct Entry { const char *name; const char *data; int size; const char *mime; };

    static const Entry entries[] = {
        { "index.html", {{PLUGIN_ID}}_UI::index_html, {{PLUGIN_ID}}_UI::index_html_size, "text/html" },
        { "style.css",  {{PLUGIN_ID}}_UI::style_css,  {{PLUGIN_ID}}_UI::style_css_size,  "text/css" },
        { "app.js",     {{PLUGIN_ID}}_UI::app_js,     {{PLUGIN_ID}}_UI::app_js_size,     "application/javascript" },
    };

    for (const auto &e : entries)
    {
        if (wanted != e.name)
            continue;

        const auto *bytes = reinterpret_cast<const std::byte *> (e.data);

        return juce::WebBrowserComponent::Resource {
            std::vector<std::byte> (bytes, bytes + static_cast<size_t> (juce::jmax (0, e.size))),
            juce::String (e.mime) };
    }

    return std::nullopt;
}

void WebViewEditor::timerCallback()
{
    auto *gainParam = m_processor.getGainParam();

    if (gainParam == nullptr)
        return;

    const auto currentGain = gainParam->get();

    if (std::abs (currentGain - m_sentGain) > 0.001f)
    {
        m_sentGain = currentGain;
        sendStateToJS();
    }
}

void WebViewEditor::sendStateToJS()
{
    // juce::var takes ownership of a heap DynamicObject, so it must not point at
    // a stack instance. app.js expects an array of state objects.
    auto *state = new juce::DynamicObject();
    state->setProperty ("type", "state");
    state->setProperty ("gain", static_cast<double> (m_sentGain));
    state->setProperty ("pluginName", juce::String ("{{PLUGIN_DISPLAY_NAME}}"));
    state->setProperty ("vendor", juce::String ("{{VENDOR}}"));

    juce::Array<juce::var> payload;
    payload.add (juce::var (state));

    const auto json = juce::JSON::toString (juce::var (payload), /*allOnOneLine=*/true);

    // C++ -> JS
    m_webView.evaluateJavascript ("window.updateState && window.updateState (" + json + ");");
}

bool WebViewEditor::handleJSAction (const juce::String &url)
{
    if (! url.startsWith ("apc://callback"))
        return false;

    const auto params = parseQuery (url);
    const auto action = params["action"];

    if (action == "setGain")
    {
        auto *gainParam = m_processor.getGainParam();

        if (gainParam != nullptr)
            *gainParam = static_cast<float> (params.getValue ("data", "1.0").getDoubleValue());
    }

    return true; // consumed — block the navigation
}
