#include "PluginProcessor.h"
#include "WebViewEditor.h"

// Binary data generated by juce_add_webview_ui
// This symbol is auto-generated from the BINARY_DATA_ID in CMakeLists.txt
namespace {{PLUGIN_ID}}_UI { extern const char *index_html; extern const int index_html_size; }

WebViewEditor::WebViewEditor({{PLUGIN_CLASS_NAME}} &p)
    : AudioProcessorEditor(&p), m_processor(p)
{
    setSize(600, 400);

    // Load embedded UI from BinaryData
    auto html = juce::String::fromUTF8(
        {{PLUGIN_ID}}_UI::index_html,
        {{PLUGIN_ID}}_UI::index_html_size
    );

    m_webView.loadHTMLString(html, "file:///");

    // Intercept JS→C++ messages via URL scheme
    m_webView.onPageAboutToLoad = [this](const juce::String &url) -> bool {
        if (!url.startsWith("apc://")) return false;
        auto params = URLParser(url);
        handleJSAction(params["action"], params["data"]);
        return true; // block navigation
    };

    addAndMakeVisible(m_webView);
    startTimerHz(30); // 30fps UI updates
}

WebViewEditor::~WebViewEditor() = default;

void WebViewEditor::resized() {
    m_webView.setBounds(getLocalBounds());
}

void WebViewEditor::timerCallback() {
    float currentGain = *m_processor.getGainParam();
    if (std::abs(currentGain - m_sentGain) > 0.001f) {
        m_sentGain = currentGain;
        sendStateToJS();
    }
}

void WebViewEditor::sendStateToJS() {
    auto json = juce::JSON::toString(juce::var(juce::Array<juce::var>{
        new juce::var(new juce::DynamicObject{
            {"type", "state"},
            {"gain", m_sentGain},
            {"pluginName", "{{PLUGIN_DISPLAY_NAME}}"},
            {"vendor", "{{VENDOR}}"}
        })
    }));

    // Call JS function with latest state
    m_webView.evaluateJavascript(
        "window.updateState && window.updateState(" + json + ");"
    );
}

void WebViewEditor::handleJSAction(const juce::String &action, const juce::var &data) {
    if (action == "setGain" && data.isDouble()) {
        *m_processor.getGainParam() = (float)data;
    }
}

static juce::StringPairArray URLParser(const juce::String &url) {
    juce::StringPairArray params;
    auto query = url.fromFirstOccurrenceOf("?", false, false);
    for (auto &part : juce::StringArray::fromTokens(query, "&", "")) {
        auto kv = juce::StringArray::fromTokens(part, "=", "");
        if (kv.size() == 2)
            params.set(kv[0].trim(), juce::URL::removeEscapeChars(kv[1].trim()));
    }
    return params;
}
